Sem-4/.net/MVCLab-6/Models/ErrorViewModel.cs
namespace MVCLab_6.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sem-4/.net/MVCLab-6/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCLab_6.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult contact()
        {
            return View();
        }
    }
}

Sem-4/.net/MVCLab-6/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCLab_6.Controllers
{
    public class FormController : Controller
    {
        public IActionResult Form()
        {
            return View();
        }
    }
}

Sem-4/.net/MVCLab-6/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVCLab_6.Models;

namespace MVCLab_6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sem-4/.net/MVCLab-6/Views/About/contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1> sdfghjk </h1>

Sem-4/.net/MVCLab-6/Views/Form/Form.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-primary-subtle">
    <div>
        <div class="container bg-light">
            <div class="bg-primary text-center">
                <i class="bi bi-geo-alt-fill fs-1"></i>
            </div>
            <div>
                <div class="text-center mt-3">
                    <h1 class="text-primary">Oredr/delivery Tracking</h1>
                    <h6 class="text-primary">Trace your order</h6>
                </div>

                <h6 class="mt-3 text-primary">Personal Information</h6>
                <hr class="text-primary">
                <div class="row mt-4">
                    <div class="col-4 text-primary">Name</div>
                    <div class="col-8"><input type="text" class="form-control text-primary" id="firstName" required></div>
                </div>
                <div class="row mt-4">
                    <div class="col-4 text-primary">Email</div>
                    <div class="col-8"><input type="email" class="form-control" id="firstName" required></div>
                </div>
                <div class="row mt-4">
                    <div class="col-4 text-primary">Contact numebr</div>
                    <div class="col-8"><input type="number" class="form-control" id="firstName" required></div>
                </div>

                <h6 class="mt-4 text-primary">Order Information</h6>
                <hr>
                <div class="row mt-4">
                    <div class="col-4 text-primary">Oredr Id</div>
                    <div class="col-8"><input type="number" class="form-control" id="firstName" required></div>
                </div>
                <div class="row mt-4">
                    <div class="col-4 text-primary">Delivery destination</div>
                    <div class="col-8">
                        <input type="number" class="form-control mt-1" id="firstName" required>
                        <div id="addressHelpBlock" class="form-text text-primary">Street Address</div>
                        <input type="number" class="form-control mt-1" id="firstName" required>
                        <div id="addressHelpBlock" class="form-text text-primary">Address Line 2</div>
                        <div class="row">
                            <div class="col-6">
                                <input type="text" class="form-control mt-1" id="firstName" required>
                                <div id="addressHelpBlock" class="form-text text-primary">City</div>
                            </div>
                            <div class="col-6">
                                <input type="text" class="form-control mt-1" id="firstName" required>
                                <div id="addressHelpBlock" class="form-text text-primary">State/Region/Province</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6">
                                <input type="text" class="form-control mt-1" id="firstName" required>
                                <div id="addressHelpBlock" class="form-text text-primary">Postal / zip Code</div>
                            </div>
                            <div class="col-6">
                                <input type="text" class="form-control mt-1" id="firstName" required>
                                <div id="addressHelpBlock" class="form-text text-primary">Country</div>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-4 text-primary">When did you place your order ?</div>
                        <div class="col-8">
                            <input type="date" class="form-control text-secondary" id="firstName" required>
                            <div id="addressHelpBlock" class="form-text text-primary">dd-MMM-yyyy</div>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary mb-3 mt-4">Submit</button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Sem-4/.net/MVCLab-6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Sem-4/.net/MVCLab-6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCLab_6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCLab_6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCLab_6</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="contact">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="Form">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVCLab_6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>