sem-5/A.Net/SEM5/Controllers/CountryController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using SEM5.Models;

namespace SEM5.Controllers
{
    public class CountryController : Controller
    {
        private IConfiguration Configuration;

        public CountryController(IConfiguration _Configuration)
        {
            Configuration = _Configuration;
        }


        #region Country List
        public IActionResult CountryList()
        {
            string connectionString = this.Configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_Country_SelectAll";
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                return View(table);
            }
        }
        #endregion


        #region Add Edit Country
        public IActionResult AddEditCountry(int? CountryID)
        {
            if (CountryID == null)
            {
                return View();
            }
            else
            {
                string connectionString = this.Configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_Country_SelectByPK";
                command.Parameters.Add("@country_id", SqlDbType.Int).Value = CountryID;
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                CountryModel country = new CountryModel();

                foreach (DataRow row in table.Rows)
                {
                    country.CountryID = Convert.ToInt32(row["CountryID"]);
                    country.CountryName = row["CountryName"].ToString();
                }
                return View(country);
            }
        }
        #endregion


        #region Delete Country
        public IActionResult DeleteCountry(int CountryID)
        {
            try
            {
                string connectionString = Configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_Country_Delete";
                    command.Parameters.Add("@country_id", SqlDbType.Int).Value = CountryID;
                    command.ExecuteNonQuery();
                }
                TempData["MessageType"] = "Deleted";
                TempData["SuccessMessage"] = "Country deleted successfully.";
                return RedirectToAction("CountryList");
            }
            catch (Exception ex)
            {
                TempData["MessageType"] = "Error";
                TempData["ErrorMessage"] = "An error occurred while deleting the Country: " + ex.Message;
                return RedirectToAction("CountryList");
            }
        }
        #endregion


        #region Country Save
        public IActionResult CountrySave(CountryModel country)
        {
            try
            {
                ModelState.Clear();
                string messageType;
                string successMessage;
                string connectionString = Configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    if (country.CountryID == null)
                    {
                        command.CommandText = "PR_Country_Insert";
                        messageType = "Inserted";
                        successMessage = "Country inserted successfully";
                    }
                    else
                    {
                        messageType = "Updated";
                        successMessage = "Country updated successfully";
                        command.CommandText = "PR_Country_Update";
                        command.Parameters.Add("@country_id", SqlDbType.Int).Value = country.CountryID;
                    }
                    command.Parameters.Add("@country_name", SqlDbType.VarChar).Value = country.CountryName;
                    command.ExecuteNonQuery();
                }
                TempData["MessageType"] = messageType;
                TempData["SuccessMessage"] = successMessage;
                return RedirectToAction("CountryList");
            }
            catch (Exception ex)
            {
                TempData["MessageType"] = "Error";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("CountryList");
            }
        }
        #endregion
    }
}

sem-5/A.Net/SEM5/Views/Country/AddEditCountry.cshtml
@model CountryModel

<div class="pagetitle">
    <h1>Add Country</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item">Country</li>
            <li class="breadcrumb-item active">Add Country</li>
        </ol>
    </nav>
</div>

<section class="section">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add Country</h5>

            <form method="post" asp-controller="Country" asp-action="CountrySave">

                <div class="row mb-3" hidden>
                    <label for="inputText" class="col-sm-3 col-form-label"><span class="text-danger fs-5">*</span> Country ID:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="CountryID">
                        <span asp-validation-for="CountryID" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="inputText" class="col-sm-3 col-form-label"><span class="text-danger fs-5">*</span> Country Name:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="CountryName" autofocus>
                        <span asp-validation-for="CountryName" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9">
                        <button class="btn btn-success" type="submit">Save</button>
                        <a class="btn btn-danger" asp-controller="Country" asp-action="CountryList">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

sem-5/A.Net/SEM5/Views/Country/CountryList.cshtml
@model DataTable
@using System.Data

<div class="pagetitle">
    <h1></h1>
    <nav>
        <ol class="breadcrumb">

            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item">Country</li>
            <li class="breadcrumb-item active">Country List</li>
        </ol>
    </nav>
</div>

<section class="section">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Country List</h5>
            <div class="d-flex justify-content-between">

                <a class="btn btn-primary" asp-controller="Country" asp-action="AddEditCountry"> Add Country </a>
            </div>
            <table class="table datatable">
                <thead class="align-content-center">
                    <tr>
                        <th>CountryName</th>
                        <th class="">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DataRow row in Model.Rows)
                    {
                        <tr>
                            <td>@row["CountryName"]</td>
                            <td>
                                <div class="d-flex justify-content-center align-items-center">
                                    <a asp-controller="Country" asp-action="AddEditCountry" asp-route-CountryID="@row["CountryID"]" class="btn btn-outline-success btn-sm me-2" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit">
                                        <i class="bi bi-pencil"></i>
                                    </a>
                                    <a asp-controller="Country" asp-action="DeleteCountry" asp-route-CountryID="@row["CountryID"]" class="btn btn-outline-danger btn-sm sweet-confirm">
                                        <i class="bi bi-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

@if (TempData["SuccessMessage"] != null)
{
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            Swal.fire({
            title: '<span style="color: #166534; font-family: Roboto, sans-serif;">@TempData["MessageType"]!</span>',
            html: '<p style="color: #4b5563; font-family: Roboto, sans-serif;">@TempData["SuccessMessage"]</p>',
            icon: 'success',
            iconColor: '#16a34a', // Green success icon
            background: '#f0fdf4', // Light green background
            confirmButtonColor: '#2563eb',
            confirmButtonText: 'OK'
            })
        })
    </script>
    TempData["MessageType"] = null;
    TempData["SuccessMessage"] = null;
}

@if (@TempData["ErrorMessage"] != null)
{
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            Swal.fire({
            title: '@TempData["MessageType"]!',
            text: '@TempData["ErrorMessage"]',
            icon: 'error',
            confirmButtonText: 'Cool'
            })
        })
    </script>
    TempData["MessageType"] = null;
    TempData["ErrorMessage"] = null;
}