sem-5/A.Net/SEM5/Controllers/StateController.cs
using System.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using SEM5.Models;

namespace SEM5.Controllers
{
    public class StateController : Controller
    {
        private IConfiguration Configuration;

        public StateController(IConfiguration _Configuration)
        {
            Configuration = _Configuration;
        }


        #region State List
        public IActionResult StateList()
        {
            string connectionString = this.Configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_State_SelectAll";
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                return View(table);
            }
        }
        #endregion


        #region Add Edit State
        public IActionResult AddEditState(int? StateID)
        {
            CountryDropDown();
            if (StateID == null)
            {
                return View();
            }
            else
            {
                string connectionString = this.Configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_State_SelectByPK";
                command.Parameters.Add("@state_id", SqlDbType.Int).Value = StateID;
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                StateModel state = new StateModel();

                foreach (DataRow row in table.Rows)
                {
                    state.StateID = Convert.ToInt32(row["StateID"]);
                    state.StateName = row["StateName"].ToString();
                    state.StateCode = row["StateCode"].ToString();
                    state.CountryID = Convert.ToInt32(row["CountryID"]);
                }
                return View(state);
            }
        }
        #endregion


        #region State Save
        public IActionResult StateSave(StateModel state)
        {
            try
            {
                string messageType;
                string successMessage;
                string connectionString = Configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    if (state.StateID == null)
                    {
                        command.CommandText = "PR_State_Insert";
                        messageType = "Inserted";
                        successMessage = "State inserted successfully";
                    }
                    else
                    {
                        messageType = "Updated";
                        successMessage = "State updated successfully";
                        command.CommandText = "PR_State_Update";
                        command.Parameters.Add("@state_id", SqlDbType.Int).Value = state.StateID;
                    }
                    command.Parameters.Add("@state_name", SqlDbType.VarChar).Value = state.StateName;
                    command.Parameters.Add("@state_code", SqlDbType.VarChar).Value = state.StateCode;
                    command.Parameters.Add("@country_id", SqlDbType.Int).Value = state.CountryID;
                    command.ExecuteNonQuery();
                }
                TempData["MessageType"] = messageType;
                TempData["SuccessMessage"] = successMessage;
                return RedirectToAction("StateList");
            }
            catch (Exception ex)
            {
                TempData["MessageType"] = "Error";
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("StateList");
            }
        }
        #endregion


        #region Delete State
        public IActionResult DeleteState(int StateID)
        {
            try
            {
                string connectionString = Configuration.GetConnectionString("ConnectionString");
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    SqlCommand command = connection.CreateCommand();
                    command.CommandType = CommandType.StoredProcedure;
                    command.CommandText = "PR_State_Delete";
                    command.Parameters.Add("@state_id", SqlDbType.Int).Value = StateID;
                    command.ExecuteNonQuery();
                }
                TempData["MessageType"] = "Deleted";
                TempData["SuccessMessage"] = "State deleted successfully.";
                return RedirectToAction("StateList");
            }
            catch (Exception ex)
            {
                TempData["MessageType"] = "Error";
                TempData["ErrorMessage"] = "An error occurred while deleting the State: " + ex.Message;
                return RedirectToAction("StateList");
            }
        }
        #endregion


        #region Country DropDown
        public void CountryDropDown()
        {
            string connectionString = this.Configuration.GetConnectionString("ConnectionString");
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_Country_DropDown";
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                List<CountryDropDownModel> countryList = new List<CountryDropDownModel>();
                foreach (DataRow row in table.Rows)
                {
                    countryList.Add(new CountryDropDownModel()
                    {
                        CountryID = Convert.ToInt32(row["CountryID"].ToString()),
                        CountryName = row["CountryName"].ToString()
                    });
                }
                ViewBag.CountryList = countryList;
            }
        }
        #endregion
    }
}

sem-5/A.Net/SEM5/Views/State/AddEditState.cshtml
@model StateModel

<div class="pagetitle">
    <h1>Add State</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item">State</li>
            <li class="breadcrumb-item active">Add State</li>
        </ol>
    </nav>
</div>

<section class="section">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add State</h5>

            <form method="post" asp-controller="State" asp-action="StateSave">

                <div class="row mb-3" hidden>
                    <label for="inputText" class="col-sm-3 col-form-label"><span class="text-danger fs-5">*</span> State ID:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="StateID">
                        <span asp-validation-for="StateID" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="inputText" class="col-sm-3 col-form-label"><span class="text-danger fs-5">*</span> State Name:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="StateName" autofocus>
                        <span asp-validation-for="StateName" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="inputText" class="col-sm-3 col-form-label"><span class="text-danger fs-5">*</span> State Code:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" asp-for="StateCode">
                        <span asp-validation-for="StateCode" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="inputText" class="col-sm-3 col-form-label"><span class="text-danger fs-5">*</span> Country:</label>
                    <div class="col-sm-9">
                        <select class="form-control" asp-for="CountryID" asp-items="@( new SelectList( ViewBag.CountryList, "CountryID", "CountryName" ) )">
                            <option selected> Select Country </option>
                        </select>
                        <span asp-validation-for="CountryID" class="text-danger"></span>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9">
                        <button class="btn btn-success" type="submit">Save</button>
                        <a class="btn btn-danger" asp-controller="State" asp-action="StateList">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

sem-5/A.Net/SEM5/Views/State/StateList.cshtml
@model DataTable
@using System.Data

<div class="pagetitle">
    <h1></h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item">State</li>
            <li class="breadcrumb-item active">State List</li>
        </ol>
    </nav>
</div>

<section class="section">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">State List</h5>
            <div class="d-flex justify-content-between">

                <a class="btn btn-primary" asp-controller="State" asp-action="AddEditState"> Add State </a>
            </div>
            <table class="table datatable">
                <thead>
                    <tr>
                        <th> State Name </th>
                        <th> State Code </th>
                        <th> Country Name </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DataRow row in Model.Rows)
                    {
                        <tr>
                            <td>@row["StateName"]</td>
                            <td>@row["StateCode"]</td>
                            <td>@row["CountryName"]</td>
                            <td>
                                <div class="d-flex justify-content-center align-items-center">
                                    <a asp-controller="State" asp-action="AddEditState" asp-route-StateID="@row["StateID"]" class="btn btn-outline-success btn-sm me-2" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit">
                                        <i class="bi bi-pencil"></i>
                                    </a>
                                    <a asp-controller="State" asp-action="DeleteState" asp-route-StateID="@row["StateID"]" class="btn btn-outline-danger btn-sm sweet-confirm">
                                        <i class="bi bi-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>

@if (TempData["SuccessMessage"] != null)
{
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            Swal.fire({
            title: '<span style="color: #166534; font-family: Roboto, sans-serif;">@TempData["MessageType"]!</span>',
            html: '<p style="color: #4b5563; font-family: Roboto, sans-serif;">@TempData["SuccessMessage"]</p>',
            icon: 'success',
            iconColor: '#16a34a', // Green success icon
            background: '#f0fdf4', // Light green background
            confirmButtonColor: '#2563eb',
            confirmButtonText: 'OK'
            })
        })
    </script>
    TempData["MessageType"] = null;
    TempData["SuccessMessage"] = null;
}

@if (@TempData["ErrorMessage"] != null)
{
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            Swal.fire({
            title: '@TempData["MessageType"]!',
            text: '@TempData["ErrorMessage"]',
            icon: 'error',
            confirmButtonText: 'Cool'
            })
        })
    </script>
    TempData["MessageType"] = null;
    TempData["ErrorMessage"] = null;
}